#ifndef COMPONENTS_NETBOXGLOBAL_CALL_ERROR_CODES_H_
#define COMPONENTS_NETBOXGLOBAL_CALL_ERROR_CODES_H_

#define WR_ERROR_HTTP_CODE_EMPTY 600
#define WR_ERROR_JSON_NOT_VALID 601
#define WR_ERROR_INTERNAL 602
#define WR_ERROR_CALL_NOT_ALLOWED 603
#define WR_ERROR_SESSION_SESSION 604
#define WR_ERROR_SESSION_GUID 605
#define WR_ERROR_COOKIE_CONFIGURE 606
#define WR_ERROR_WRONG_PARAMS 610
#define WR_ERROR_ENCRYPTION_FAILED 611
#define WR_ERROR_SET_WALLET_FAIL 612
#define WR_ERROR_GET_WALLET_FAIL 613
#define WR_ERROR_DECRYPTION_FAILED 614
#define WR_ERROR_LOCAL_FUNCTION_ERROR 615
#define WR_ERROR_RESPONSE_NOT_JSON 616
#define WR_ERROR_RESPONSE_FALSE_RESULT 608

#endif